Repository 202212-GIZ-YE-FEW/DevSquad, pull requests merged in 2023-04, with the labels that each got.

#28 Footer Component
  src/components/Footer/__test__/Footer.test.js
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/Homepage/__test__/Homepage.test.js
  src/components/Homepage/__test__/__snapshots__/Homepage.test.js.snap
  src/components/Homepage/index.jsx
  src/layout/Layout.jsx
  src/pages/index.jsx
Labels: enhancement

#29 design event creation page
  public/images/Sitting.png
  public/images/google.png
  public/images/twitter.png
  src/components/Checkboxcomponent/__test__/Checkboxcomponent.test.jsx
  src/components/Checkboxcomponent/__test__/__snapshots__/Checkboxcomponent.test.jsx.snap
  src/components/Checkboxcomponent/index.jsx
  src/components/Eventcreation/__test__/Eventcreation.test.jsx
  src/components/Eventcreation/__test__/__snapshots__/Eventcreation.test.jsx.snap
  src/components/Eventcreation/index.jsx
  src/components/Homepage/Goalimage/index.jsx
  src/components/Homepage/__test__/__snapshots__/Homepage.test.js.snap
  src/components/Inputcomponent/__test__/Inputcomponent.test.jsx
  src/components/Inputcomponent/__test__/__snapshots__/Inputcomponent.test.jsx.snap
  src/components/Inputcomponent/index.jsx
  src/components/Navbar/Index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/SignIn/__test__/__snapshots__/SignIn.test.js.snap
  src/components/SignIn/index.jsx
  src/components/SignUp/Images/Sitting.png
  src/components/SignUp/Images/google.png
  src/components/SignUp/Images/twitter.png
  src/components/SignUp/__test__/__snapshots__/SignUp.test.js.snap
  src/components/SignUp/index.jsx
  src/pages/_app.jsx
  src/pages/eventcreation.jsx
  src/pages/signin.jsx
  src/pages/signup.jsx
  src/styles/navbar.css
Labels: bug, enhancement

#32 event card
  package-lock.json
  package.json
  public/images/Name.png
  public/images/Rectangle2.png
  src/components/Eventcard/__test__/Eventcard.test.jsx
  src/components/Eventcard/__test__/__snapshots__/Eventcard.test.jsx.snap
  src/components/Eventcard/index.jsx
  src/components/Eventcreation/__test__/__snapshots__/Eventcreation.test.jsx.snap
  src/components/Eventcreation/index.jsx
  src/pages/index.jsx
  tailwind.config.js
Labels: enhancement

#37 API Configuration
  config/firebase.js
  firebase-debug.log
  package-lock.json
  package.json
  src/pages/index.jsx
Labels: Develop

#40 pagination
  package-lock.json
  package.json
  src/components/Homepage/__test__/__snapshots__/Homepage.test.js.snap
  src/components/PaginationComponent/Pagination.jsx
  src/components/PaginationComponent/__test__/PaginationComponent.test.jsx
  src/components/PaginationComponent/__test__/__snapshots__/PaginationComponent.test.jsx.snap
  src/components/PaginationComponent/index.jsx
  src/components/PaginationComponent/usePagination.jsx
  src/pages/index.jsx
Labels: enhancement

#41 25 develop view event page
  .env
  .gitignore
  config/firebase.js
  src/components/EventImage/__test__/EventImage.test.js
  src/components/EventImage/__test__/__snapshots__/EventImage.test.js.snap
  src/components/EventImage/index.jsx
  src/components/EventView/__test__/__snapshots__/EventView.test.js.snap
  src/components/EventView/index.jsx
  src/pages/eventPage/[id].jsx
  src/pages/eventview.jsx
  src/pages/index.jsx
Labels: Develop

#39 develop authentication signupsignin
  .env
  .gitignore
  config/firebase.js
  package-lock.json
  package.json
  src/components/Buttoncomponent/__test__/__snapshots__/Buttoncomponent.test.js.snap
  src/components/Buttoncomponent/index.jsx
  src/components/EventView/__test__/__snapshots__/EventView.test.js.snap
  src/components/Eventcreation/__test__/__snapshots__/Eventcreation.test.jsx.snap
  src/components/Inputcomponent/index.jsx
  src/components/ProfilePage/__test__/__snapshots__/ProfilePage.test.js.snap
  src/components/SignIn/__test__/SignIn.test.js
  src/components/SignIn/__test__/__snapshots__/SignIn.test.js.snap
  src/components/SignIn/index.jsx
  src/components/SignUp/__test__/SignUp.test.js
  src/components/SignUp/__test__/__snapshots__/SignUp.test.js.snap
  src/components/SignUp/index.jsx
Labels: Develop

#42 develop Navbar
  src/components/Homepage/__test__/__snapshots__/Homepage.test.js.snap
  src/components/Navbar/Index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
Labels: Develop

#46 develop user profile page
  src/components/Buttoncomponent/index.jsx
  src/components/Checkboxcomponent/__test__/__snapshots__/Checkboxcomponent.test.jsx.snap
  src/components/Checkboxcomponent/index.jsx
  src/components/EventView/__test__/EventView.test.js
  src/components/EventView/__test__/__snapshots__/EventView.test.js.snap
  src/components/EventView/index.jsx
  src/components/Eventcreation/__test__/__snapshots__/Eventcreation.test.jsx.snap
  src/components/Eventinerestcomponent/__test__/__snapshots__/Eventinerestcomponent.test.jsx.snap
  src/components/Navbar/Index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/ProfilePage/__test__/ProfilePage.test.js
  src/components/ProfilePage/__test__/__snapshots__/ProfilePage.test.js.snap
  src/components/ProfilePage/index.jsx
Labels: Develop

#49 translate home page
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Eventcreation/__test__/__snapshots__/Eventcreation.test.jsx.snap
  src/components/Eventcreation/index.jsx
  src/components/Eventinerestcomponent/__test__/__snapshots__/Eventinerestcomponent.test.jsx.snap
  src/components/Eventinerestcomponent/index.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/Getstartedbtn/__test__/__snapshots__/Getstartedbtn.test.jsx.snap
  src/components/Getstartedbtn/index.jsx
  src/components/Homepage/Hirosection/__test__/__snapshots__/Hirosection.test.js.snap
  src/components/Homepage/Hirosection/index.jsx
  src/components/Homepage/HowitworkCard/__test__/__snapshots__/HowitworkCard.test.jsx.snap
  src/components/Homepage/HowitworkCard/index.jsx
  src/components/Homepage/__test__/__snapshots__/Homepage.test.js.snap
  src/components/Homepage/index.jsx
  src/components/Navbar/Index.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/layout/Layout.jsx
  src/pages/aboutpage.jsx
  src/pages/events.jsx
  src/pages/index.jsx
Labels: design, translate

#51 design events page
  src/components/Calendar/__test__/__snapshots__/Calendar.test.js.snap
  src/components/Calendar/index.jsx
  src/components/Eventcard/__test__/__snapshots__/Eventcard.test.jsx.snap
  src/components/Eventcard/index.jsx
  src/components/Eventinerestcomponent/__test__/__snapshots__/Eventinerestcomponent.test.jsx.snap
  src/components/Eventinerestcomponent/index.jsx
  src/components/Eventslist/__test__/Eventslist.test.jsx
  src/components/Eventslist/__test__/__snapshots__/Eventslist.test.jsx.snap
  src/components/Eventslist/index.jsx
  src/components/Homepage/__test__/__snapshots__/Homepage.test.js.snap
  src/components/PaginationComponent/Pagination.jsx
  src/components/PaginationComponent/__test__/__snapshots__/PaginationComponent.test.jsx.snap
  src/components/PaginationComponent/index.jsx
  src/pages/events.jsx
Labels: design

#52 develop create event page
  .env
  src/components/Checkboxcomponent/index.jsx
  src/components/Eventcreation/__test__/Eventcreation.test.jsx
  src/components/Eventcreation/__test__/__snapshots__/Eventcreation.test.jsx.snap
  src/components/Eventcreation/index.jsx
  src/components/Gmap/__test__/Gmap.test.js
  src/components/Gmap/__test__/__snapshots__/Gmap.test.js.snap
  src/components/Gmap/index.js
  src/utils/types.js
Labels: Develop

#55 Update README.md
  README.md
Labels: documentation, enhancement

#54 26 develop events page
  src/components/EventView/__test__/__snapshots__/EventView.test.js.snap
  src/components/EventView/index.jsx
  src/components/Eventcard/__test__/__snapshots__/Eventcard.test.jsx.snap
  src/components/Eventcard/index.jsx
  src/components/Eventslist/__test__/Eventslist.test.jsx
  src/components/Eventslist/__test__/__snapshots__/Eventslist.test.jsx.snap
  src/components/Eventslist/index.jsx
  src/components/PaginationComponent/__test__/PaginationComponent.test.jsx
  src/components/PaginationComponent/__test__/__snapshots__/PaginationComponent.test.jsx.snap
  src/components/PaginationComponent/index.jsx
  src/components/ProfilePage/index.jsx
  src/components/SignIn/index.jsx
  src/components/SignUp/index.jsx
Labels: Develop

#63 feat(404 page): design 404 page
  src/components/Aboutpage/Aboutpage.jsx
  src/pages/404.jsx
Labels: design

#66 64 develop navbar image
  src/components/EventImage/index.jsx
  src/components/EventView/__test__/__snapshots__/EventView.test.js.snap
  src/components/EventView/index.jsx
  src/components/Homepage/__test__/__snapshots__/Homepage.test.js.snap
  src/components/Navbar/Index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
Labels: Develop
