Repository 202212-GIZ-YE-FEW/DevSquad, pull requests merged in 2023-05, with the labels that each got.

#70 Develop Events Page
  src/components/Calendar/CalendarComponent/index.jsx
  src/components/Calendar/__test__/__snapshots__/Calendar.test.js.snap
  src/components/Calendar/index.jsx
  src/components/Eventcard/index.jsx
  src/components/Eventinerestcomponent/__test__/__snapshots__/Eventinerestcomponent.test.jsx.snap
  src/components/Eventinerestcomponent/index.jsx
  src/components/Eventslist/__test__/__snapshots__/Eventslist.test.jsx.snap
  src/components/Eventslist/index.jsx
  src/components/PaginationComponent/Pagination.jsx
  src/components/PaginationComponent/paginate.jsx
  src/components/PaginationComponent/usePagination.jsx
  src/pages/events.jsx
Labels: Develop

#69 feat(add translation to about page): add Arabic language to about page
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Aboutpage/Aboutpage.jsx
  src/components/Aboutpage/__test__/__snapshots__/Aboutpage.test.js.snap
Labels: enhancement

#75 feat(add translate to calendar): add Arabic language to Calendar
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Calendar/__test__/__snapshots__/Calendar.test.js.snap
  src/components/Calendar/index.jsx
  src/components/Eventslist/__test__/__snapshots__/Eventslist.test.jsx.snap
Labels: enhancement, translate

#76 73 add translate to sign in and sign out components
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/SignIn/__test__/__snapshots__/SignIn.test.js.snap
  src/components/SignIn/index.jsx
  src/components/SignUp/__test__/__snapshots__/SignUp.test.js.snap
  src/components/SignUp/index.jsx
Labels: enhancement, translate

#95 add validation updateUserProfile
  src/components/ProfilePage/__test__/__snapshots__/ProfilePage.test.js.snap
  src/components/ProfilePage/index.jsx
Labels: enhancement, Develop

#105 perf(eventview): add-validation-joinEvent
  src/components/EventView/index.jsx
  src/components/PaginationComponent/index.jsx
Labels: enhancement, Develop

#103 101 add translation to profile page and events page
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/EventView/__test__/__snapshots__/EventView.test.js.snap
  src/components/EventView/index.jsx
  src/components/Eventcard/__test__/__snapshots__/Eventcard.test.jsx.snap
  src/components/Eventcard/index.jsx
  src/components/Eventcreation/__test__/__snapshots__/Eventcreation.test.jsx.snap
  src/components/Eventcreation/index.jsx
  src/components/Eventinerestcomponent/__test__/__snapshots__/Eventinerestcomponent.test.jsx.snap
  src/components/Eventinerestcomponent/index.jsx
  src/components/Eventslist/__test__/__snapshots__/Eventslist.test.jsx.snap
  src/components/Eventslist/index.jsx
  src/components/LocationComponent/__test__/__snapshots__/LocationComponent.test.jsx.snap
  src/components/LocationComponent/index.jsx
  src/components/PaginationComponent/Pagination.jsx
  src/components/ProfilePage/__test__/__snapshots__/ProfilePage.test.js.snap
  src/components/ProfilePage/index.jsx
Labels: enhancement, translate

#109 94 add attendance
  .env
  src/components/EventImage/index.jsx
  src/components/EventView/index.jsx
  src/components/Eventcard/index.jsx
  src/components/Eventslist/__test__/__snapshots__/Eventslist.test.jsx.snap
  src/components/Eventslist/index.jsx
  src/components/Navbar/Index.jsx
  src/components/PaginationComponent/index.jsx
  src/components/ProfilePage/index.jsx
  src/components/SignUp/index.jsx
Labels: bug, Develop

#110 fixed the filtering issue
  src/components/Calendar/CalendarComponent/index.jsx
  src/components/Calendar/index.jsx
  src/components/DialogBox/__test__/DialogBox.test.js
  src/components/DialogBox/__test__/__snapshots__/DialogBox.test.js.snap
  src/components/DialogBox/index.jsx
  src/components/Eventinerestcomponent/__test__/Eventinerestcomponent.test.jsx
  src/components/Eventinerestcomponent/__test__/__snapshots__/Eventinerestcomponent.test.jsx.snap
  src/components/Eventinerestcomponent/index.jsx
  src/components/Eventslist/__test__/__snapshots__/Eventslist.test.jsx.snap
  src/components/Eventslist/index.jsx
  src/components/LocationComponent/__test__/__snapshots__/LocationComponent.test.jsx.snap
  src/components/LocationComponent/index.jsx
Labels: Develop

#114 108 add translation to alert
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/DialogBox/index.jsx
  src/components/EventView/index.jsx
  src/components/Eventcreation/index.jsx
  src/components/Eventslist/index.jsx
  src/components/PaginationComponent/index.jsx
  src/components/ProfilePage/index.jsx
  src/components/SignUp/index.jsx
Labels: enhancement, translate

#116 add validation
  .env
  src/components/SignIn/index.jsx
  src/components/SignUp/index.jsx
Labels: Develop
